apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isproxy
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isproxy.dev.intern.nav.no"
    - "https://isproxy.dev-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isnarmesteleder
          namespace: teamsykefravr
          cluster: dev-gcp
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://isproxy.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvisproxy
        mountPath: /secrets/serviceuser/isproxy
  webproxy: true
  env:
    - name: KTOR_ENV
      value: "production"
    - name: EREG_URL
      value: "https://modapp-q1.adeo.no"
    - name: SECURITY_TOKEN_SERVICE_URL
      value: "https://security-token-service.nais.preprod.local"
    - name: DOKDIST_URL
      value: "https://dokdistfordeling-q1.nais.preprod.local"
    - name: SYFOSYKETILFELLE_URL
      value: "https://syfosyketilfelle.nais.preprod.local"
