apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isproxy
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - "https://isproxy.intern.nav.no"
    - "https://isproxy.prod-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: prod-gcp
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://isproxy.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvisproxy
        mountPath: /secrets/serviceuser/isproxy
  webproxy: true
  env:
    - name: KTOR_ENV
      value: "production"
    - name: STS_SAML_URL
      value: "https://sts.adeo.no/SecurityTokenServiceProvider/"
    - name: FASTLEGE_URL
      value: "https://pep-gw.oera.no:9443/ekstern/helse/fastlegeinformasjon"
    - name: ADRESSEREGISTER_URL
      value: "https://pep-gw.oera.no:9443/ekstern/helse/adresseregisteret/v1"
