apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isproxy
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - "https://isproxy.dev.intern.nav.no"
    - "https://isproxy.dev-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: padm2
          namespace: teamsykefravr
          cluster: dev-gcp
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://isproxy.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvisproxy
        mountPath: /secrets/serviceuser/isproxy
  webproxy: true
  env:
    - name: KTOR_ENV
      value: "production"
    - name: BTSYS_URL
      value: "https://btsys.nais.preprod.local"
    - name: KUHRSAR_CLIENT_ID
      value: "dev-fss.teamkuhr.kuhr-sar-api"
    - name: KUHRSAR_URL
      value: "https://kuhr-sar-api.dev.adeo.no"
    - name: SECURITY_TOKEN_SERVICE_URL
      value: "https://security-token-service.nais.preprod.local"
    - name: STS_SAML_URL
      value: "https://sts-q1.preprod.local/SecurityTokenServiceProvider/"
    - name: FASTLEGE_URL
      value: "https://pep-gw-q4.oera-q.local:9443/ekstern/helse/fastlegeinformasjon"
    - name: ADRESSEREGISTER_URL
      value: "https://pep-gw-q4.oera-q.local:9443/ekstern/helse/adresseregisteret/v1"
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: "https://wasapp-q1.adeo.no/nav-emottak-eletter-web/services/"
